import "./EmblemCard.scss";
import adeptasororitas from "../../assets/emblems/adepta-sororitas-crest.svg";
import adeptuscustodes from "../../assets/emblems/adeptus-custodes-crest.svg";
import adeptusmechanicus from "../../assets/emblems/adeptus-mechanicus-crest.svg";
import aelderi from "../../assets/emblems/aelderi-crest.svg";
import astramilitarum from "../../assets/emblems/astra-militarum-crest.svg";
import badmoons from "../../assets/emblems/bad-moons.svg";
import barrowkings from "../../assets/emblems/barrowkings.svg";
import beastmen from "../../assets/emblems/beastmen.svg";
import blackdragons from "../../assets/emblems/black-dragons.svg";
import bloodangels from "../../assets/emblems/bloodangels-crest.svg";
import centurionhonor from "../../assets/emblems/centurion-honour.svg";
import chaosspacemarines from "../../assets/emblems/chaos-space-marines-crest.svg";
import chaosdemons from "../../assets/emblems/chaosdemons-crest.svg";
import daemonsofkhorne from "../../assets/emblems/daemons-of-khorne.svg";
import daemonsofnurgle from "../../assets/emblems/daemons-of-nurgle.svg";
import darkelves from "../../assets/emblems/dark-elves.svg";
import darkangels from "../../assets/emblems/darkangels-crest.svg";
import darktemplars from "../../assets/emblems/darktemplars-crest.svg";
import deathguard from "../../assets/emblems/deathguard-crest.svg";
import deathwatch from "../../assets/emblems/deathwatch-crest.svg";
import drukhari from "../../assets/emblems/drukhari-crest.svg";
import dwarf from "../../assets/emblems/dwarf.svg";
import empire from "../../assets/emblems/empire.svg";
import falshia from "../../assets/emblems/falshia.svg";
import genestealercult from "../../assets/emblems/genestealer-cult-crest.svg";
import greyknights from "../../assets/emblems/greyknights-crest.svg";
import highelves from "../../assets/emblems/high-elves.svg";
import leaguesofvotann from "../../assets/emblems/leaguesofvotann-crest.svg";
import lizardmen from "../../assets/emblems/lizardmen.svg";
import kroot from "../../assets/emblems/kroot.svg";
import metalica from "../../assets/emblems/metalica.svg";
import necrons from "../../assets/emblems/necrons-crest.svg";
import nightgoblins from "../../assets/emblems/night-goblins.svg";
import ogrekingdoms from "../../assets/emblems/ogre-kingdoms.svg";
import orcsandgoblins from "../../assets/emblems/orcs-and-goblins.svg";
import orks from "../../assets/emblems/orks-crest.svg";
import savageorcs from "../../assets/emblems/savage-orcs.svg";
import skaven from "../../assets/emblems/skaven.svg";
import slaanesh from "../../assets/emblems/slaanesh.svg";
import spacemarines from "../../assets/emblems/spacemarines-crest.svg";
import spacewolves from "../../assets/emblems/spacewolves-crest.svg";
import tau from "../../assets/emblems/t'au-crest.svg";
import thousandsons from "../../assets/emblems/thousandsons-crest.svg";
import tyrannids from "../../assets/emblems/tyrannids-crest.svg";
import tzeentchdaemons from "../../assets/emblems/tzeentch-daemons.svg";
import vampirecounts from "../../assets/emblems/vampire-counts.svg";
import warpspiders from "../../assets/emblems/warp-spiders.svg";
import warriorsofchaoskhorne from "../../assets/emblems/warriors-of-chaos-khorne.svg";
import warriorsofchaosnurgle from "../../assets/emblems/warriors-of-chaos-nurgle.svg";
import warriorsofchaostzeentch from "../../assets/emblems/warriors-of-chaos-tzeentch.svg";
import warriorsofchaos from "../../assets/emblems/warriors-of-chaos.svg";
import woodelves from "../../assets/emblems/wood-elves.svg";
import worldeaters from "../../assets/emblems/worldeaters-crest.svg";
import ultramarines from "../../assets/emblems/ultramarines.svg";
import salamanders from "../../assets/emblems/salamanders.svg";
import whitescars from "../../assets/emblems/whitescars.svg";
import snakebites from "../../assets/emblems/snakebites.svg";
import gofforks from "../../assets/emblems/gofforks.svg";
import bloodaxes from "../../assets/emblems/bloodaxes.svg";

type EmblemType = {
  emblem: string;
};

export default function EmblemCard({ emblem }: EmblemType) {
  let emblemIcon = tau;

  emblem === "adeptasororitas"
    ? (emblemIcon = adeptasororitas)
    : emblem === "adeptuscustodes"
    ? (emblemIcon = adeptuscustodes)
    : emblem === "adeptusmechanicus"
    ? (emblemIcon = adeptusmechanicus)
    : emblem === "aelderi"
    ? (emblemIcon = aelderi)
    : emblem === "astramilitarum"
    ? (emblemIcon = astramilitarum)
    : emblem === "badmoons"
    ? (emblemIcon = badmoons)
    : emblem === "blackdragons"
    ? (emblemIcon = blackdragons)
    : emblem === "barrowkings"
    ? (emblemIcon = barrowkings)
    : emblem === "beastmen"
    ? (emblemIcon = beastmen)
    : emblem === " bloodangels"
    ? (emblemIcon = bloodangels)
    : emblem === "bloodaxes"
    ? (emblemIcon = bloodaxes)
    : emblem === "centurionhonor"
    ? (emblemIcon = centurionhonor)
    : emblem === "chaosspacemarines"
    ? (emblemIcon = chaosspacemarines)
    : emblem === "chaosdemons"
    ? (emblemIcon = chaosdemons)
    : emblem === "daemonsofkhorne"
    ? (emblemIcon = daemonsofkhorne)
    : emblem === "daemonsofnurgle"
    ? (emblemIcon = daemonsofnurgle)
    : emblem === "darkelves"
    ? (emblemIcon = darkelves)
    : emblem === "darkangels"
    ? (emblemIcon = darkangels)
    : emblem === "darktemplars"
    ? (emblemIcon = darktemplars)
    : emblem === "deathguard"
    ? (emblemIcon = deathguard)
    : emblem === "deathwatch"
    ? (emblemIcon = deathwatch)
    : emblem === "drukhari"
    ? (emblemIcon = drukhari)
    : emblem === "dwarf"
    ? (emblemIcon = dwarf)
    : emblem === "empire"
    ? (emblemIcon = empire)
    : emblem === "falshia"
    ? (emblemIcon = falshia)
    : emblem === "genestealercult"
    ? (emblemIcon = genestealercult)
    : emblem === "greyknights"
    ? (emblemIcon = greyknights)
    : emblem === "gofforks"
    ? (emblemIcon = gofforks)
    : emblem === "highelves"
    ? (emblemIcon = highelves)
    : emblem === "leaguesofvotann"
    ? (emblemIcon = leaguesofvotann)
    : emblem === "lizardmen"
    ? (emblemIcon = lizardmen)
    : emblem === "kroot"
    ? (emblemIcon = kroot)
    : emblem === "metalica"
    ? (emblemIcon = metalica)
    : emblem === "necrons"
    ? (emblemIcon = necrons)
    : emblem === "nightgoblins"
    ? (emblemIcon = nightgoblins)
    : emblem === "ogrekingdoms"
    ? (emblemIcon = ogrekingdoms)
    : emblem === "orcsandgoblins"
    ? (emblemIcon = orcsandgoblins)
    : emblem === "orks"
    ? (emblemIcon = orks)
    : emblem === "salamanders"
    ? (emblemIcon = salamanders)
    : emblem === "savageorcs"
    ? (emblemIcon = savageorcs)
    : emblem === "skaven"
    ? (emblemIcon = skaven)
    : emblem === "slaanesh"
    ? (emblemIcon = slaanesh)
    : emblem === "snakebites"
    ? (emblemIcon = snakebites)
    : emblem === "spacemarines"
    ? (emblemIcon = spacemarines)
    : emblem === "spacewolves"
    ? (emblemIcon = spacewolves)
    : emblem === "tau"
    ? (emblemIcon = tau)
    : emblem === "thousandsons"
    ? (emblemIcon = thousandsons)
    : emblem === "tyrannids"
    ? (emblemIcon = tyrannids)
    : emblem === "tzeentchdaemons"
    ? (emblemIcon = tzeentchdaemons)
    : emblem === "vampirecounts"
    ? (emblemIcon = vampirecounts)
    : emblem === "warpspiders"
    ? (emblemIcon = warpspiders)
    : emblem === "warriorsofchaoskhorne"
    ? (emblemIcon = warriorsofchaoskhorne)
    : emblem === "warriorsofchaosnurgle"
    ? (emblemIcon = warriorsofchaosnurgle)
    : emblem === "warriorsofchaostzeentch"
    ? (emblemIcon = warriorsofchaostzeentch)
    : emblem === "warriorsofchaos"
    ? (emblemIcon = warriorsofchaos)
    : emblem === "whitescars"
    ? (emblemIcon = whitescars)
    : emblem === "woodelves"
    ? (emblemIcon = woodelves)
    : emblem === "worldeaters"
    ? (emblemIcon = worldeaters)
    : emblem === "ultramarines"
    ? (emblemIcon = ultramarines)
    : (emblemIcon = necrons);

  return <img className="emblem-card" src={emblemIcon} alt="army emblem" />;
}
