export const emblemNameArray = [
  {
    fortyk: [
      "Tau",
      "Orks",
      "Necrons",
      "Leagues of Votann",
      "Genestealer Cult",
      "Tyrannids",
      "Drukhari",
      "Aelderi",
      "Chaos Demons",
      "World Eaters",
      "Thousand Sons",
      "Death Guard",
      "Chaos Space Marines",
      "Astra Militarum",
      "Adeptus Mechanicus",
      "Adeptus Custodes",
      "Adepta Sororitas",
      "Space Wolves",
      "Grey Knights",
      "Death Watch",
      "Dark Angels",
      "Blood Angels",
      "Space Marines",
      "Salamanders",
      "Ultramarines",
      "White Scars",
      "Snake Bites",
      "Goff Orks",
      "Blood Axes",
      "Falshia",
      "Kroot",
      "Bad Moons",
      "Warp Spiders",
      "Metalica",
      "Black Dragons",
      "Centurion Honor",
    ],
    fantasy: [
      "Skaven",
      "Tzeentch Daemons",
      "High Elves",
      "Daemons of Nurgle",
      "Wood Elves",
      "Empire",
      "Lizardmen",
      "Warriors of Chaos Tzeentch",
      "Warriors of Chaos",
      "Warriors of Chaos Nurgle",
      "Slaanesh",
      "Dark Elves",
      "Beastmen",
      "Warriors of Chaos Khorne",
      "Daemons of Khorne",
      "Dwarf",
      "Vampire Counts",
      "Barrowkings",
      "Night Goblins",
      "Ogre Kingdoms",
      "Orcs and Goblins",
      "Savage Orcs",
    ],
  },
];
