import { Battle } from "../../utils/Interfaces";

export const mockBattles: Battle[] = [
  {
    id: "battle-001",
    date: "2025-06-08",
    scenario: "Eternal War",
    points_size: 2000,
    result: "Victory",
    winner: "player-001",
    battle_type: "40k",
    player_type: "single",
    player_1: [
      {
        id: "player-001",
        name: "Space Marines",
        known_as: "The Imperium",
        ranking: "2500",
        army_id: "army-001",
        emblem: "space-marine-emblem",
      },
    ],
    player_2: [
      {
        id: "player-002",
        name: "Chaos Space Marines",
        known_as: "Chaos Undivided",
        ranking: "2200",
        army_id: "army-002",
        emblem: "chaos-emblem",
      },
    ],
    player_1_points: 85,
    player_2_points: 42,
    table: "Table 1",
    finish: "14:30",
    start: "12:00",
    combatant_1_id: "user-001",
    combatant_2_id: "user-002",
    user_1_id: "user-001",
    user_2_id: "user-002",
  },
  {
    id: "battle-002",
    date: "2025-06-05",
    scenario: "Battleline",
    points_size: 1500,
    result: "Defeat",
    winner: "player-003",
    battle_type: "fantasy",
    player_type: "single",
    player_1: [
      {
        id: "player-001",
        name: "Empire",
        known_as: "The Empire",
        ranking: "1800",
        army_id: "army-004",
        emblem: "empire-emblem",
      },
    ],
    player_2: [
      {
        id: "player-003",
        name: "Orcs  Goblins",
        known_as: "Greenskins",
        ranking: "1650",
        army_id: "army-005",
        emblem: "orc-emblem",
      },
    ],
    player_1_points: 35,
    player_2_points: 78,
    table: "Table 2",
    finish: "16:45",
    start: "14:00",
    combatant_1_id: "user-001",
    combatant_2_id: "user-003",
    user_1_id: "user-001",
    user_2_id: "user-003",
  },
];
